### ISSUE TITLE
Investigating bad self-mapping of a dataset

### ISSUE THREAD

**Issue by mxposed** [hemberg-lab/scmap#10]
Hello. I'm trying to use `scmap` to analyse several related datasets that I have and encountered a problem: my reference dataset maps badly to itself (scmap-cluster method, kappa score 0.017 and unassigned fraction of 52%). I've tried to initialise `logcounts` to `log2(rawcounts + 1)`, to seurat's normalised counts and to seurat's scaled counts. The first two strategies yield almost the same result, and the last one results in this error: “scmap index is empty because the median expression in the selected features is 0 in every cell cluster!”. I think I'm doing something wrong with the initialisation of `SingleCellExperiment`, or probably with using scmap, but I don't know how to investigate that. I will be glad for any suggestions

**Comment by wikiselev** [comment]
Hello, thanks for your question! If it is a 10X experiment with a lot of cells this is a known issue. In this case our feature selection method does not perform as well as for other experimental protocols due to the large number of cells and the sequencing depth. You could try to use some other feature selection method to select features to be used with `scmap`. Please have a look here - #3 - on how to do that. Regarding the error that you receive it is probably related to the issue with feature selection, because the median expression is 0 in all cell types for the selected features.

**Comment by mxposed** [comment]
Thank you for your answer. I will try to select features with some other method. By the way, do you know if including all feature in `selectFeatures` should improve accuracy of self-mapping or not?

**Comment by wikiselev** [comment]
No, in our experience selecting more than 1000 features dramatically reduces the accuracy of mapping, please check the paper for more details.

**Comment by mxposed** [comment]
Thank you! Seurat's feature selection seems to work quite well
