### ISSUE TITLE
selectFeatures() Error

### ISSUE THREAD

**Issue by lololiam** [hemberg-lab/scmap#13]
Hi,

I'm attempting to use scmap on an object that I have converted from Seurat to SCE with Seurats `Convert()` function.

When attempting to call `selectFeatures()`, I receive the following error:

`Error in rowSums(count == 0) :    'x' must be an array of at least two dimensions`

I looked through the code on the following pages:
[Core Methods](https://github.com/hemberg-lab/scmap/blob/master/R/CoreMethods.R)
[Utils](https://github.com/hemberg-lab/scmap/blob/master/R/Utils.R)

It looks like these lines from the `linearModel()` function are causing the error:

`count <- as.matrix(counts(object))`
`dropouts <- rowSums(count == 0)/cols * 100`

I am confused though, as if I simply run these lines in isolation, I receive no errors and my 'count==0' matrix is a normal sized matrix (i.e. at least two dimensions), and I don't see anything else in the code where it might have changed in a way to cause this error, as from my understanding, the object I'm passing to `selectFeatures` is passed to linearModel which then pulls out the counts so running the two lines in isolation should also cause the error?

Any advice would be greatly appreciated,

Liam

**Comment by wikiselev** [comment]
Hi Liam, sorry for a very long delay, did you manage to make it working?

**Comment by VBRay** [comment]
I have encountered the same problem。My matrix is  20125(rows) * 8569(cols)，and the sce object contains counts in its assays.

**Comment by lixin4306ren** [comment]
Hi, @VBRay 

How did you solve this problem? I encountered the same problem. Thanks in advance.

**Comment by homopolymer** [comment]
I have the same problem. How to solve it?

**Comment by VBRay** [comment]
> I have the same problem. How to solve it?

you should probably make sure that the counts ,logcounts or normcounts included in assays(sce)  are matrix property.

**Comment by leonfodoulian** [comment]
Hi @wikiselev,

I recently tried running this function and encountered the same error when using `scmap` version 1.4.1 (the `Bioconductor` version):

```R
> packageVersion(pkg = "scmap")
[1] ‘1.4.1’
```

The error was due to the fact that my `counts`, `normcounts` and `logcounts` matrices were sparse matrices.

Below is a `traceback()` of the error:

```R
> sce <- selectFeatures(object = sce, suppress_plot = FALSE)
Error in rowSums(count == 0) : 
  'x' must be an array of at least two dimensions
> traceback()
5: stop("'x' must be an array of at least two dimensions")
4: rowSums(count == 0)
3: linearModel(object, n_features)
2: selectFeatures(object = sce, suppress_plot = FALSE)
1: selectFeatures(object = sce, suppress_plot = FALSE)
```

However, when I installed `scmap` from GitHub, the function worked perfectly well. Therefore, it seems to me that few lines of code have been removed from `scmap::linearModel()` in the `Bioconductor` version, specifically that which transform `counts` to an object of class `matrix` (see line 150 in [Utils.R](https://github.com/hemberg-lab/scmap/blob/master/R/Utils.R#L150)).

I don't find it convenient to store `counts`, `normcounts` and `logcounts` in class `matrix` in my `SingleCellExperiment` object as the data with which I am currently working is quite large, and transforming these sparse matrices to class `matrix` significantly inflates in the time it takes to create the `SingleCellExperiment` object (sometimes causing my `R` session to crash and restart).

Would it be possible to ensure that future versions of `scmap` handle sparse matrices using the `Matrix` package?

Best,
Leon

**Comment by wikiselev** [comment]
Hi Leon, many thanks for your description and sorry for my late reply. Unfortunately, we don't have anyone who can support scmap at the moment, therefore no further modifications are planned. If you can create a pull request and could test it and merge to master.

**Comment by leonfodoulian** [comment]
Hi @wikiselev,

Thank you for your answer. There is no need to create a pull request in GitHub as this version of `scmap` works as expected. I think that if no major changes exist between the GitHub version or the `Bioconductor` version, then maybe you could submit the GitHub version of `scmap` to the `Bioconductor` repository?

Best,
Leon
